language: php

php:
- '7.1'
- '7.2'

install: [
  "mkdir -p app/etc var",
  "echo \"{\\\"http-basic\\\":{\\\"repo.magento.com\\\":{\\\"username\\\":\\\"${MAGENTO_USERNAME}\\\",\\\"password\\\":\\\"${MAGENTO_PASSWORD}\\\"}}}\" > auth.json",
  "composer install --prefer-dist"
  ]

cache:
  directories:
    - $HOME/.composer/cache

script:
    - vendor/bin/phpcs --config-set installed_paths vendor/magento/marketplace-eqp/
    - vendor/bin/phpcs --standard=vendor/magento/marketplace-eqp/MEQP2 --severity=9 .
    - vendor/bin/phpcpd --exclude Test --exclude vendor --progress .
    - vendor/bin/phpmd --suffixes php,phtml . text cleancode,codesize,controversial,design,naming,unusedcode
    - vendor/bin/phpunit -c Resources/tests/unit/phpunit.xml
