sudo: required
dist: trusty

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - postfix

language: php

jobs:
  include:
    - php: 7.1
      env:
        - MAGENTO_VERSION=2.3.0 MAGENTO_EDITION=community
    - if: type != pull_request
      php: 7.1
      env:
        - MAGENTO_VERSION=2.3.0 MAGENTO_EDITION=enterprise
    - php: 7.2
      env:
        - MAGENTO_VERSION=2.3.0 MAGENTO_EDITION=community
    - if: type != pull_request
      php: 7.2
      env:
        - MAGENTO_VERSION=2.3.0 MAGENTO_EDITION=enterprise

before_install:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then composer config -g http-basic.repo.magento.com $MAGENTO_USERNAME $MAGENTO_PASSWORD ; fi
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
  - composer global require hirak/prestissimo:0.3.4
  - chmod +x ./Resources/travis/*
  - ./Resources/travis/prepare_php.sh
  - ./Resources/travis/before_install.sh

install:
  - composer install --prefer-dist

cache:
  directories:
    - $HOME/.composer/cache

script:
  - ./Resources/travis/test_magento.sh
  - vendor/bin/phpcs --config-set installed_paths vendor/magento/marketplace-eqp/
  - vendor/bin/phpcs --standard=vendor/magento/marketplace-eqp/MEQP2 --severity=9 src/
  - vendor/bin/phpunit -c Resources/tests/unit/phpunit.xml
