sudo: required
dist: trusty

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - postfix

language: php
env:
  global:
    - REPOSITORY=https://github.com/angeldm/magento2-command-cleanner.git
    - MODULE_NAME=angeldm/magento2-command-cleanner
    - MODULE_SLUG=Angeldm\Cleanner

jobs:
  include:
    - php: 7.1
      env:
        - MAGENTO_VERSION=2.3.1 MAGENTO_EDITION=community

before_install:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then composer config --global http-basic.repo.magento.com "$MAGENTO_USERNAME" "$MAGENTO_PASSWORD"; fi
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
  - sh -c "if [ ! -e composer.json ]; then composer init -n; fi"
  - composer global require hirak/prestissimo
  - chmod +x ./Resources/travis/*
  - ./Resources/travis/prepare_php.sh
  - ./Resources/travis/before_install.sh

install:
  - composer install --prefer-dist

cache:
  directories:
    - $HOME/.composer/cache

script:
  - ./Resources/travis/test_magento.sh
  - vendor/bin/phpcs --config-set installed_paths vendor/magento/marketplace-eqp/
  - vendor/bin/phpcs --standard=vendor/magento/marketplace-eqp/MEQP2 --severity=9 .
  - vendor/bin/phpcpd --exclude Test --exclude vendor --progress .
  - vendor/bin/phpmd --suffixes php,phtml . text cleancode,codesize,controversial,design,naming,unusedcode
  - vendor/bin/phpunit -c Resources/tests/unit/phpunit.xml
